# Docker compose to run local fast API and a Postgres database
version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  web:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"
