"""One delete updates

Revision ID: 1251bd18eb95
Revises: cfb5d8c65658
Create Date: 2024-04-10 00:02:16.609124

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1251bd18eb95"
down_revision: Union[str, None] = "cfb5d8c65658"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
