"""One delete updates

Revision ID: 1efa816c77bf
Revises: 5eade0279df7
Create Date: 2024-04-09 23:56:48.206438

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1efa816c77bf"
down_revision: Union[str, None] = "5eade0279df7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("vm_inventory_product_id_fkey", "vm_inventory", type_="foreignkey")
    op.create_foreign_key(None, "vm_inventory", "vm_product", ["product_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint("vm_product_created_by_fkey", "vm_product", type_="foreignkey")
    op.create_foreign_key(None, "vm_product", "vm_users", ["created_by"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vm_product", type_="foreignkey")
    op.create_foreign_key("vm_product_created_by_fkey", "vm_product", "vm_users", ["created_by"], ["id"])
    op.drop_constraint(None, "vm_inventory", type_="foreignkey")
    op.create_foreign_key("vm_inventory_product_id_fkey", "vm_inventory", "vm_product", ["product_id"], ["id"])
    # ### end Alembic commands ###
